// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuL-KvLAWWLQy6MnY1HZseJ0OPyWGa2ig',
    appId: '1:605182874473:android:8d09e74195a2a850f623f8',
    messagingSenderId: '605182874473',
    projectId: 'messanger-feeac',
    databaseURL: 'https://messanger-feeac-default-rtdb.firebaseio.com',
    storageBucket: 'messanger-feeac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcFUwM1ZAqEuv7uXQOGd5neWxgmEuOy_Q',
    appId: '1:605182874473:ios:db26d937eb98288bf623f8',
    messagingSenderId: '605182874473',
    projectId: 'messanger-feeac',
    databaseURL: 'https://messanger-feeac-default-rtdb.firebaseio.com',
    storageBucket: 'messanger-feeac.appspot.com',
    iosClientId: '605182874473-rqg1mo1i6tsc7ig5d7bs58r8rcgv0ptk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMessengerApp',
  );
}
